language: c
build:
  pre_ci:
    - mkdir -p mybuild
    - cp ./tests/docker/dockerfiles/debian-multiarch-cross.docker mybuild/Dockerfile
    - docker build -t debian-multiarch-cross:tip mybuild
  pre_ci_boot:
    image_name: debian-multiarch-cross
    image_tag: tip
    pull: false
    options: "-e HOME=/root"
  ci:
    - sudo apt-get update -qq
    - apt-get build-dep -a armhf -qq qemu
    - ./configure --cross-prefix=arm-linux-gnueabihf-
    - make -j3
    - make test
