language: c
env:
  global:
    - LC_ALL=C
    # sometimes Shippable fails to clone from github (git_sync stage):
    # "Problem with the SSL CA cert (path? access rights?)"
    # for now disable SSL verification.
    - GIT_SSL_NO_VERIFY=1
  matrix:
    - IMAGE=debian-armhf-cross
      TARGET_LIST=arm-softmmu,arm-linux-user
    - IMAGE=debian-arm64-cross
      TARGET_LIST=aarch64-softmmu,aarch64-linux-user
    - IMAGE=debian-s390x-cross
      TARGET_LIST=s390x-softmmu,s390x-linux-user
    - IMAGE=debian-mipsel-cross
      TARGET_LIST=mipsel-softmmu,mips64el-softmmu,mipsel-linux-user,mips64el-linux-user
build:
  pre_ci:
    - make docker-image-${IMAGE}
  pre_ci_boot:
    image_name: qemu
    image_tag: ${IMAGE}
    pull: false
    options: "-e HOME=/root"
  ci:
    - unset CC
    - ./configure ${QEMU_CONFIGURE_OPTS} --target-list=${TARGET_LIST}
    - make -j$(getconf _NPROCESSORS_ONLN)
