---
- name: Installation of basic packages to build QEMU
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: Install basic packages to build QEMU on Ubuntu 18.04
      apt:
        update_cache: yes
        # This matches the packages on tests/docker/Dockerfiles/ubuntu1804.docker
        pkg:
          - flex
          - bison
          - ccache
          - clang
          - gcc
          - gettext
          - git
          - glusterfs-common
          - libaio-dev
          - libattr1-dev
          - libbrlapi-dev
          - libbz2-dev
          - libcacard-dev
          - libcap-ng-dev
          - libcurl4-gnutls-dev
          - libdrm-dev
          - libepoxy-dev
          - libfdt-dev
          - libgbm-dev
          - libgtk-3-dev
          - libibverbs-dev
          - libiscsi-dev
          - libjemalloc-dev
          - libjpeg-turbo8-dev
          - liblzo2-dev
          - libncurses5-dev
          - libncursesw5-dev
          - libnfs-dev
          - libnss3-dev
          - libnuma-dev
          - libpixman-1-dev
          - librados-dev
          - librbd-dev
          - librdmacm-dev
          - libsasl2-dev
          - libsdl2-dev
          - libseccomp-dev
          - libsnappy-dev
          - libspice-protocol-dev
          - libspice-server-dev
          - libssh-dev
          - libusb-1.0-0-dev
          - libusbredirhost-dev
          - libvdeplug-dev
          - libvte-2.91-dev
          - libxen-dev
          - libzstd-dev
          - make
          - python3-yaml
          - python3-sphinx
          - sparse
          - texinfo
          - xfslibs-dev
        state: present
      when: "ansible_facts['distribution'] == 'Ubuntu'"

    - name: Install basic packages to build QEMU on FreeBSD 12.x
      pkgng:
        # This matches the packages on .cirrus.yml under the freebsd_12_task
        name: bash,bison,curl,cyrus-sasl,git,glib,gmake,gnutls,gsed,nettle,perl5,pixman,pkgconf,png,usbredir
        state: present
      when: "ansible_facts['os_family'] == 'FreeBSD'"

    - name: Install basic packages to build QEMU on Fedora 30
      dnf:
        # This matches the packages on tests/docker/Dockerfiles/fedora.docker
        name:
          - bc
          - bison
          - brlapi-devel
          - bzip2
          - bzip2-devel
          - ccache
          - clang
          - cyrus-sasl-devel
          - dbus-daemon
          - device-mapper-multipath-devel
          - findutils
          - flex
          - gcc
          - gcc-c++
          - gettext
          - git
          - glib2-devel
          - glusterfs-api-devel
          - gnutls-devel
          - gtk3-devel
          - hostname
          - libaio-devel
          - libasan
          - libattr-devel
          - libblockdev-mpath-devel
          - libcap-ng-devel
          - libcurl-devel
          - libfdt-devel
          - libiscsi-devel
          - libjpeg-devel
          - libpmem-devel
          - libpng-devel
          - librbd-devel
          - libseccomp-devel
          - libssh-devel
          - libubsan
          - libusbx-devel
          - libxml2-devel
          - llvm
          - lzo-devel
          - make
          - mingw32-bzip2
          - mingw32-curl
          - mingw32-glib2
          - mingw32-gmp
          - mingw32-gnutls
          - mingw32-gtk3
          - mingw32-libjpeg-turbo
          - mingw32-libpng
          - mingw32-libtasn1
          - mingw32-nettle
          - mingw32-nsis
          - mingw32-pixman
          - mingw32-pkg-config
          - mingw32-SDL2
          - mingw64-bzip2
          - mingw64-curl
          - mingw64-glib2
          - mingw64-gmp
          - mingw64-gnutls
          - mingw64-gtk3
          - mingw64-libjpeg-turbo
          - mingw64-libpng
          - mingw64-libtasn1
          - mingw64-nettle
          - mingw64-pixman
          - mingw64-pkg-config
          - mingw64-SDL2
          - ncurses-devel
          - nettle-devel
          - nss-devel
          - numactl-devel
          - perl
          - perl-Test-Harness
          - pixman-devel
          - python3
          - python3-sphinx
          - PyYAML
          - rdma-core-devel
          - SDL2-devel
          - snappy-devel
          - sparse
          - spice-server-devel
          - systemd-devel
          - systemtap-sdt-devel
          - tar
          - texinfo
          - usbredir-devel
          - virglrenderer-devel
          - vte291-devel
          - which
          - xen-devel
          - zlib-devel
          - libzstd-devel
        state: present
      when: "ansible_facts['distribution'] == 'Fedora'"

    - name: Install basic packages to build QEMU on CentOS 8
      dnf:
        # This matches the packages on tests/docker/Dockerfiles/centos8.docker
        name:
          - SDL-devel
          - bison
          - bzip2
          - bzip2-devel
          - dbus-daemon
          - flex
          - gcc
          - gcc-c++
          - gettext
          - git
          - glib2-devel
          - libaio-devel
          - libepoxy-devel
          - lzo-devel
          - make
          - mesa-libEGL-devel
          - nettle-devel
          - perl-Test-Harness
          - pixman-devel
          - python36
          - rdma-core-devel
          - spice-glib-devel
          - spice-server
          - tar
          - zlib-devel
        state: present
      when:
        - "ansible_facts['distribution'] == 'CentOS'"
        - "ansible_facts['distribution_major_version'] == '8'"
